[package]
name = "blockchain_rust"
version = "0.1.0"
authors = ["Andrey Kamakin <a.kamakin@icloud.com>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
serde_derive = "1.0.89"
serde = "1.0.89"
bincode = "1.1.2"
